### ISSUE TITLE
Error document is not defined when connect channel by nuxt

### ISSUE THREAD

**Issue by revan2006** [adonisjs/adonis-websocket-client#21]
Hello,
not sure if it real issue, but you can't connect to channel it error document is not defined ('node_modules\adonis-websocket-client\dist\ws.js'). in here my code:

`import Vue from 'vue' import ws from 'adonis-websocket-client' const wsVuePlugin = function (Vue, url, options) { Vue.prototype.$io = ws(url, options) } Vue.use(wsVuePlugin, 'http://localhost:3000', {})`

`export default { created: function () { this.$io.channel('chat').connect(console.log) } }`

**Comment by mtnptrsn** [comment]
I'm also trying to implement adonis-websocket-client in my nuxt app and can't find a sulotion.

**Comment by thetutlage** [comment]
Nuxt does SSR and `document` is only defined in browsers.

So make sure Websocket client is ignored during SSR

**Comment by mtnptrsn** [comment]
@thetutlage Yup. I realised I didn't have the same error after all. I just forgot to add the babel polyfill. If someone is running in to the same problem, the only thing I did was:
1. Install babel-polyfill (`yarn add babel-polyfill`)
2. Add babel-polyfill to nuxt.config.json's build.vendor (`build: {vendor: ['babel-polyfill']}`)

**Comment by thetutlage** [comment]
Thanks for sharing the resolution too 😄
