### ISSUE TITLE
VueJS and channel connect

### ISSUE THREAD

**Issue by mikield** [adonisjs/adonis-websocket-client#22]
When connecting to the socket without `token` query param and trying to connect to channel with `withJwt()` method - if fails.

Connection URL: `ws://localhost:8081/socket.io/EIO=3&transport=websocket&sid=w9gDx_6eLxRiffcRAAAD`

Result of connect to channel: 
![deepinscreenshot_select-area_20170918040316](https://user-images.githubusercontent.com/4073672/30527211-9ba86a82-9c26-11e7-8b46-cffe0b407dd9.png)

But after refresh, the connection is with `token` query param and connection to the channel is ok.

Connection URL:
`ws://localhost:8081/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVpZCI6MX0sImlhdCI6MTUwNTcwMDE3NCwiZXhwIjoxNTA1Nzg2NTc0fQ.vA-4Cekta05M6IOKQiCXq42rLuf6wTA1qeGcWjK3bA0&EIO=3&transport=websocket&sid=HKc7o7ftvSxidnfSAAAB`

Result of connect to channel: 
![deepinscreenshot_select-area_20170918040859](https://user-images.githubusercontent.com/4073672/30527285-278c4960-9c27-11e7-8414-ed63b4d5e1ec.png)

Maybe there is a option to reconect to the sockets with `token` in query?

I have this situation when user is going from guest to auth mode.
So from login page to dashboard page.

**Comment by mikield** [comment]
This is maybe the issue #20 

I am connection to the public channel and after login trying to connect to private channel with JWT token

**Comment by reg2005** [comment]
For vue you can use [adonis-vue-websocket](https://github.com/reg2005/adonis-vue-websocket) plugin
