### ISSUE TITLE
adonis-websocket-vue repo not found

### ISSUE THREAD

**Issue by jagroop** [adonisjs/adonis-websocket-client#37]
Hi, is this repo deleted?

https://github.com/adonisjs/adonis-websocket-vue

It is referenced in Readme.

Thanks.

**Comment by ftaurino** [comment]
up

**Comment by borie88** [comment]
down again

**Comment by jagroop** [comment]
@thetutlage ??

**Comment by thetutlage** [comment]
Yup, the repo is not available right now. I will see, when I can write a plugin for Vue.

**Comment by WelaurS** [comment]
up

**Comment by jakesylvestre** [comment]
@thetutlage in the future can we archive these instead of deleting them? It's helpful for those of us that end up using the old code to write one

**Comment by thetutlage** [comment]
Repo was never created. I planned to work on it at the same time, but never got the time to do same

**Comment by hadihammurabi** [comment]
Can we open this ISSUE again? I am waiting for this plugin

**Comment by allenhark** [comment]
Agreed, can we get old code and update?

**Comment by RomainLanz** [comment]
You don't need to have this plugin to work with Adonis Websocket.
I have three Vue applications using the vanilla client and it work well.

If you have trouble doing so, please open a thread on the [forum](https://forum.adonisjs.com) or join our [Discord Server](https://discord.gg/vDcEjq6).
