### ISSUE TITLE
Bower 'Failed to read' error

### ISSUE THREAD

**Issue by mertindervish** [adonisjs/adonis-websocket-client#5]
Hi. I'm trying to install adonis-websocket-client with bower but the missing comma from the [#31](https://github.com/adonisjs/adonis-websocket-client/blob/develop/bower.json#L31) line of bower.json throws `Failed to read` error. I hope you fix it as soon as possible. Have a good day :smile:

**Comment by RomainLanz** [comment]
Hey ! 

May you send a PR ? ❤️
