### ISSUE TITLE
Disable console logs

### ISSUE THREAD

**Issue by vaneetjoshi** [adonisjs/adonis-websocket-client#50]
i am new to nodejs and adonisjs and struggling hard to learn them, i am trying to use adonis web socket client and it is now working fine but i have one issue i am not able to remove console logs provided by default with adonisjs, can anyone please provide step by step instructions to remove console logs in browser

**Comment by jakesylvestre** [comment]
This can be done by setting `proccess.env.NODE_ENV` to anything but production. I've gone ahead and opened up #53 to make this easier to do by adding a `debug` option.

**Comment by vaneetjoshi** [comment]
i figured out some other and easy way to do this simply use https://unpkg.com/@adonisjs/websocket-client@1.0.9/dist/Ws.browser.min.js this js file and everything will work fine

**Comment by nandordudas** [comment]
If somebody else use it with Nuxt, here is an example:
[Nuxt module](https://gist.github.com/nandordudas/846bd0e56a3f242e69310d5176489176)

**Comment by reg2005** [comment]
Its simply! I'am used it in my VueJS projects (VueCLI 3)

before:
```js
import Ws from '@adonisjs/websocket-client'
```

after:
```js
import Ws from '@adonisjs/websocket-client/index'
```
