### ISSUE TITLE
Is that possible to adapt for React Native?

### ISSUE THREAD

**Issue by vpsantos** [adonisjs/adonis-websocket-client#56]
I have a React Native app with Adonis backend where I am implementing a chat system with Websockets, so I would like to use Adonis Websocket client as well.

I have an error to connect, as window.location.protocol and window.location.host don't exist without the browser.

Would be possible to handle the code to make everything work fine?

Thanks!

**Comment by RomainLanz** [comment]
Closing in favor of this PR https://github.com/adonisjs/adonis-websocket-client/pull/42
