### ISSUE TITLE
How to use websocket with flutter

### ISSUE THREAD

**Issue by hkmsadek** [adonisjs/adonis-websocket-client#62]
Hi is it possible to use websocket in flutter? They have a nice package for pure websocket 
https://pub.dev/packages/web_socket_channel

I was able to connect websocket from the app and also was able to receive data from adonis server. But I am not being able to send data from flutter app adonis.

Is there implementation for flutter? Thank you.

**Comment by ConsoleTVs** [comment]
Having similar issues here, how did you manage to subsribe to a channel?

**Comment by ConsoleTVs** [comment]
Well, I spent a whole day to create a websocket package (`websok`: https://pub.dev/packages/websok) based on `web_socket_channel`, and another package to use adonis websockets with it: (`adonis_websok`: https://pub.dev/packages/adonis_websok)

Consider using `adonis_websok` to use adonisjs websockets in flutter. **This may be closed now :)**

**Comment by RomainLanz** [comment]
Thanks for your time on this package.
Closing.
