### ISSUE TITLE
Trying to close a channel and subscribing to it after throws an error

### ISSUE THREAD

**Issue by mtsbxavier** [adonisjs/adonis-websocket-client#68]
If I connect to a channel:

```
this.channel = ws.subscribe('channel');
```
Close its connection:

```
this.channel.close();
```
And then try to subscribe to the same channel after I closed it:
```
this.channel = ws.subscribe('channel');
```
The client throws an error with the message "Cannot join the same topic twice".

One would say: You can use getSubscription() to get the active subscription instead of trying to connect to it again. But the getSubscription() method doesn't return closed subscriptions.

Is this the expected behavior?

**Comment by ekpono** [comment]
I am getting the same error. Please I need help to sort this out
