### ISSUE TITLE
ws.connect is not a functio

### ISSUE THREAD

**Issue by devalexandre** [adonisjs/adonis-websocket-client#70]
I use with react but display it

index.js?41f5:15 Uncaught TypeError: ws.connect is not a function

```js
		const ws =  Ws('ws://192.168.0.101:3333')
				ws.connect()
```
https://github.com/adonisjs/adonis-websocket-client/blob/develop/src/Connection/index.js#L583

**Comment by RomainLanz** [comment]
Hey! 👋 

Your issue do not follow our guidelines.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [forum](https://forum.adonisjs.com/) or [discord server](https://discord.gg/vDcEjq6?)


**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
