### ISSUE TITLE
adonis-websocket-client on android 

### ISSUE THREAD

**Issue by apatche7** [adonisjs/adonis-websocket-client#9]
adonis-websocket-client can use in website what if I want to use it on android? cause, I'm making web services for android and, I'm using socket chat, adonis-websocket is so good i like it :), but I can't use it on android, Is there any solution.

**Comment by RomainLanz** [comment]
Hey @apatche7!

The `adonis-websocket-client` as been build on purpose to be used in a browser environment. Native Android development has nothing to do with that.

You need to find a package or create one that can handle Websocket in Java.

**Comment by apatche7** [comment]
Understood, Was ask if your team made a one for Java, Thank you so much. :)

**Comment by utsavstha** [comment]
This post is very old but I have created an Android client for adonis websockets.
Hopefully this will be helpful for others.
https://github.com/utsavstha/adonis-websocket-client-android
